"""Initial

Revision ID: 2859bf89a481
Revises:
Create Date: 2024-07-21 18:34:51.494385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2859bf89a481'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'apps',
        sa.Column('UUID', sa.UUID(), nullable=False),
        sa.Column('kind', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column(
            'state',
            sa.Enum('new', 'installing', 'running', name='status'),
            nullable=True,
        ),
        sa.Column('json', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('UUID'),
    )
    op.create_index(op.f('ix_apps_UUID'), 'apps', ['UUID'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apps_UUID'), table_name='apps')
    op.drop_table('apps')
    # ### end Alembic commands ###
